#!/bin/bash
CURDIR=$(cd "$(dirname "$0")"; pwd)
docker run -d --name starcoin-faucet-api-server -p 8000:8000 \
    -e "STARCOIN_FAUCET_DEBUG=${STARCOIN_FAUCET_DEBUG}" \
    -e "STARCOIN_FAUCET_CELERY_REDIS_BROKER_ADDRESS=${STARCOIN_FAUCET_CELERY_REDIS_BROKER_ADDRESS}" \
    -e "STARCOIN_FAUCET_CELERY_REDIS_BACKEND_ADDRESS=${STARCOIN_FAUCET_CELERY_REDIS_BACKEND_ADDRESS}" \
    -e "STARCOIN_FAUCET_REDIS_DSN=${STARCOIN_FAUCET_REDIS_DSN}" \
    -e "STARCOIN_FAUCET_SQLALCHEMY_DATABASE_URI=${STARCOIN_FAUCET_SQLALCHEMY_DATABASE_URI}" \
    -e "STARCOIN_FAUCET_PRIVATE_KEY_BARNARD=${STARCOIN_FAUCET_PRIVATE_KEY_BARNARD}" \
    -e "STARCOIN_FAUCET_PRIVATE_KEY_HALLEY=${STARCOIN_FAUCET_PRIVATE_KEY_HALLEY}" \
    -e "STARCOIN_FAUCET_PRIVATE_KEY_PROXIMA=${STARCOIN_FAUCET_PRIVATE_KEY_PROXIMA}" \
    starcoin-faucet-api-server:latest

docker ps


