apiVersion: apps/v1
kind: Deployment
metadata:
  name: faucet-api-deployment
  labels:
    app: faucet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faucet-api
  template:
    metadata:
      labels:
        app: faucet-api
    spec:
      containers:
        - name: faucet-api
          image: starcoin/starcoin-faucet-api:0.4.3
          ports:
            - containerPort: 8000
          env:
            - name: STARCOIN_FAUCET_DEBUG
              value: "False"
            - name: STARCOIN_FAUCET_MYSQL_HOST
              value: "starcoin-db-2.c0bz9kehdvnb.ap-northeast-1.rds.amazonaws.com"
            - name: STARCOIN_FAUCET_MYSQL_PORT
              value: "3306"
            - name: STARCOIN_FAUCET_MYSQL_DB
              value: "faucet"
            - name: STARCOIN_FAUCET_MYSQL_USER
              value: "starcoin"
            - name: STARCOIN_FAUCET_MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-pwd
                  key: password
            - name: STARCOIN_FAUCET_PRIVATE_KEY_BARNARD
              valueFrom:
                secretKeyRef:
                  name: faucet-account
                  key: privatekey
            - name: STARCOIN_FAUCET_PRIVATE_KEY_PROXIMA
              valueFrom:
                secretKeyRef:
                  name: faucet-account
                  key: privatekey
            - name: STARCOIN_FAUCET_PRIVATE_KEY_HALLEY
              valueFrom:
                secretKeyRef:
                  name: faucet-account
                  key: privatekey
            - name: STARCOIN_FAUCET_API_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: faucet-api-session-secret
                  key: session_secret
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key-id
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: "us-west-2"
            - name: AWS_SENDER
              value: "westar@gmail.com"
            - name: AWS_RECIPIENT
              value: "westar@gmail.com"
            - name: AWS_FAUCET_SUBJECT
              value: "Faucet fails"
