apiVersion: v1
kind: Service
metadata:
  labels:
    app: faucet-api
  name: faucet-api
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8000
  selector:
    app: faucet-api
  type: LoadBalancer
status:
  loadBalancer: {}