"""empty message

Revision ID: 0fa0e175cdad
Revises: d757fdf185eb
Create Date: 2021-09-05 21:22:39.258121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fa0e175cdad'
down_revision = 'd757fdf185eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_records_address', table_name='airdrop_records')
    op.drop_table('airdrop_records')
    op.drop_table('airdrop_token_list')
    op.drop_index('idx_records_address2', table_name='airdrop_records2')
    op.drop_table('airdrop_records2')
    op.drop_index('unique_address', table_name='orders')
    op.drop_table('orders')
    op.drop_table('order')
    op.drop_index('idx_projects_network_version', table_name='airdrop_projects')
    op.drop_table('airdrop_projects')
    op.drop_table('airdrop_amount')
    op.drop_table('poll_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_item',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('creator', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('for_votes', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('against_votes', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('end_time', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('network', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('type_args_1', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('title_en', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=5000), nullable=False),
    sa.Column('description_en', mysql.VARCHAR(length=5000), nullable=False),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=False),
    sa.Column('create_at', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id_on_chain', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', 'network'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('airdrop_amount',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=45), nullable=True),
    sa.Column('amount', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('idx', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('proof', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=500), nullable=True),
    sa.Column('project_id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('air_drop_id', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('owner_address', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=45), nullable=True),
    sa.Column('root', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=45), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('airdrop_projects',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_bin', length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_bin', length=45), server_default=sa.text("'0x1::STC::STC'"), nullable=False),
    sa.Column('token_icon', mysql.VARCHAR(collation='utf8mb4_bin', length=100), server_default=sa.text("''"), nullable=True),
    sa.Column('token_symbol', mysql.VARCHAR(collation='utf8mb4_bin', length=45), server_default=sa.text("'STC'"), nullable=False),
    sa.Column('token_precision', mysql.INTEGER(), server_default=sa.text("'9'"), autoincrement=False, nullable=True),
    sa.Column('total_amount', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('valid_amount', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('start_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('end_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('owner_address', mysql.VARCHAR(collation='utf8mb4_bin', length=45), nullable=True),
    sa.Column('root', mysql.VARCHAR(collation='utf8mb4_bin', length=100), nullable=True),
    sa.Column('network_version', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('create_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('update_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_projects_network_version', 'airdrop_projects', ['network_version'], unique=False)
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address', mysql.VARCHAR(length=34), nullable=True, comment='address'),
    sa.Column('tradeaddr', mysql.CHAR(length=255), nullable=False, comment='交易地址'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='收件人'),
    sa.Column('phone', mysql.CHAR(length=14), nullable=False, comment='电话号码'),
    sa.Column('area', mysql.VARCHAR(length=255), nullable=False, comment='邮寄地址'),
    sa.Column('zipcode', mysql.CHAR(length=6), nullable=False, comment='邮编'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address', mysql.VARCHAR(length=34), nullable=False, comment='address'),
    sa.Column('tradeaddr', mysql.CHAR(length=255), nullable=False, comment='交易地址'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='收件人'),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('area', mysql.VARCHAR(length=255), nullable=False, comment='邮寄地址'),
    sa.Column('street', mysql.VARCHAR(length=255), nullable=False, comment='街道地址'),
    sa.Column('zipcode', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_address', 'orders', ['address'], unique=True)
    op.create_table('airdrop_records2',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=45), nullable=True),
    sa.Column('amount', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('idx', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('proof', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=1000), nullable=True),
    sa.Column('airdrop_id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['airdrop_id'], ['airdrop_projects.id'], name='fk_airdrop_id2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_records_address2', 'airdrop_records2', ['address'], unique=False)
    op.create_table('airdrop_token_list',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=45), nullable=True),
    sa.Column('code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('airdrop_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address', mysql.VARCHAR(collation='utf8mb4_bin', length=45), nullable=True),
    sa.Column('amount', mysql.BIGINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('idx', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('proof', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=1000), nullable=True),
    sa.Column('airdrop_id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['airdrop_id'], ['airdrop_projects.id'], name='fk_airdrop_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_records_address', 'airdrop_records', ['address'], unique=False)
    # ### end Alembic commands ###
