"""empty message

Revision ID: 540355d5a987
Revises: 
Create Date: 2021-09-05 19:39:10.129596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540355d5a987'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
