"""empty message

Revision ID: 7b449c975883
Revises: 0d2a6b6c437a
Create Date: 2022-01-30 14:18:06.335852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b449c975883'
down_revision = '0d2a6b6c437a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faucet', sa.Column('scrape_retry', sa.SmallInteger(), nullable=True))
    op.add_column('faucet', sa.Column('transfer_retry', sa.SmallInteger(), nullable=True))
    op.create_index('ix_faucet_address_network', 'faucet', ['address', 'network'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_faucet_address_network', table_name='faucet')
    op.drop_column('faucet', 'transfer_retry')
    op.drop_column('faucet', 'scrape_retry')
    # ### end Alembic commands ###
