"""empty message

Revision ID: a91dc1d4ce6a
Revises: 540355d5a987
Create Date: 2021-09-05 19:45:30.443236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91dc1d4ce6a'
down_revision = '540355d5a987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faucet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('transfered_txn', sa.String(length=128), nullable=True),
    sa.Column('transfered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faucet_id'), 'faucet', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faucet_id'), table_name='faucet')
    op.drop_table('faucet')
    # ### end Alembic commands ###
