"""empty message

Revision ID: aea964c92497
Revises: 
Create Date: 2022-01-31 00:27:57.804570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aea964c92497'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faucet_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('transfered_txn', sa.String(length=128), nullable=True),
    sa.Column('transfered_at', sa.DateTime(), nullable=True),
    sa.Column('scrape_retry', sa.SmallInteger(), nullable=True),
    sa.Column('transfer_retry', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faucet_address_address'), 'faucet_address', ['address'], unique=False)
    op.create_index(op.f('ix_faucet_address_id'), 'faucet_address', ['id'], unique=False)
    op.create_index('ix_faucet_address_network', 'faucet_address', ['address', 'network'], unique=False)
    op.create_index('ix_faucet_platform_transfered_at_status', 'faucet_address', ['platform', 'transfered_at', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_faucet_platform_transfered_at_status', table_name='faucet_address')
    op.drop_index('ix_faucet_address_network', table_name='faucet_address')
    op.drop_index(op.f('ix_faucet_address_id'), table_name='faucet_address')
    op.drop_index(op.f('ix_faucet_address_address'), table_name='faucet_address')
    op.drop_table('faucet_address')
    # ### end Alembic commands ###
