"""empty message

Revision ID: cb6e2bd9f225
Revises: a91dc1d4ce6a
Create Date: 2021-09-05 19:55:54.242938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6e2bd9f225'
down_revision = 'a91dc1d4ce6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_faucet_address'), 'faucet', ['address'], unique=False)
    op.create_index('platform_url', 'faucet', ['platform', 'url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('platform_url', table_name='faucet')
    op.drop_index(op.f('ix_faucet_address'), table_name='faucet')
    # ### end Alembic commands ###
