"""empty message

Revision ID: d757fdf185eb
Revises: cb6e2bd9f225
Create Date: 2021-09-05 20:06:25.613783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd757fdf185eb'
down_revision = 'cb6e2bd9f225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_faucet_platform_transfered_at_status', 'faucet', ['platform', 'transfered_at', 'status'], unique=False)
    op.drop_index('platform_url', table_name='faucet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('platform_url', 'faucet', ['platform', 'url'], unique=False)
    op.drop_index('ix_faucet_platform_transfered_at_status', table_name='faucet')
    # ### end Alembic commands ###
